motor_params:
  n_motors: 6
  a: 0.77522
  b: -1.2348

mrs_uav_managers:

  constraint_manager:

    # list of allowed constraints per odometry mode
    allowed_constraints:
      gps_garmin: ["slow", "medium", "fast"]
      gps_baro: ["slow", "medium", "fast"]
      rtk: ["slow", "medium", "fast"]
      rtk_garmin: ["slow", "medium", "fast"]
      aloam: ["slow"]
      hector_garmin: ["slow"]
      vio: ["slow"]
      optflow: ["slow"]
      other: ["slow"]
      ground_truth: ["slow", "medium", "fast"]
      passthrough: ["slow", "medium", "fast"]
