# Motor thrust curve parameters
# a - quadratic term
# b - constant term
# n_motors - number of motors on the UAV

motor_params:
  a: 0.348
  b: -0.215
  n_motors: 4

mrs_uav_managers:
  
  estimation_manager:

    state_estimators: [
      "gps_baro",
    ]

    initial_state_estimator: "gps_baro"

    agl_height_estimator: ""

  gain_manager:

    supersoft:

      mass_estimator:

        km: 0.05 # [kg/s], mass estimator max rate

    soft:

      mass_estimator:

        km: 0.05 # [kg/s], mass estimator max rate

mrs_uav_controllers:

  mpc_controller:

    so3:

      mass_estimator:

        km: 0.05 # [kg/s], mass estimator max rate
