image_width: 752
image_height: 480
camera_name: bluefox_front
camera_matrix:
  rows: 3
  cols: 3
  data: [610.4122 ,   0.     , 364.01562,
           0.     , 607.49757, 249.60757,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.404329, 0.162735, -0.010924, 0.000652, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [503.31339,   0.     , 359.3689 ,   0.     ,
           0.     , 565.8114 , 246.45002,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
