image_width: 1280
image_height: 720
camera_name: mobius
camera_matrix:
  rows: 3
  cols: 3
  data: [887.95062,   0.     , 686.16048,
           0.     , 999.81132, 402.36409,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.369529, 0.118566, -0.002602, 0.001124, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [678.15497,   0.     , 715.04375,   0.     ,
           0.     , 944.92804, 405.29885,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
