network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [10.10.20.101/24]
  wifis:
    wlan0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.69.101/24]
      gateway4: 192.168.69.1
      access-points:
        "wifi_ssid":
          password: "wifi_password"
      nameservers:
        addresses: [8.8.8.8]
        
