mrs_uav_managers:

  estimation_manager:

    state_estimators: [
     "aloam"
    ]

    initial_state_estimator: "aloam" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

    # namespace of the state estimator
    aloam:

      address: "aloam/AloamEstimatorPlugin"

      requires: # data required from the hw api
        gnss: false
        imu: false
        distance_sensor: false
        altitude: false
        magnetometer_heading: false
        position: false
        orientation: true
        velocity: false
        angular_velocity: true

      override_frame_id: # override the default frame_id with a custom one (e.g. slam_origin instead of aloam_origin)
        enabled: true
        frame_id: "slam_origin" # the desired frame_id without the UAV namespace

      estimators: # the names of the partial estimators
        lateral:
          name: "lat_aloam"
        altitude:
          name: "alt_aloam"
        heading:
          name: "hdg_aloam"
          passthrough: false # if true, then heading is not estimated but passed through from the orientation topic

      topics:
        orientation: "hw_api/orientation" # orientation passthrough
        angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough

      # namespace of the altitude estimator
      alt_aloam: 

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)
 
        innovation:
          limit: 1.0 # [m] innovation limit that will trigger action
          action: "switch" # {"eland", "switch", "mitigate"}
  
        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: true
          buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)
  
        process_noise: # process noise covariance (Q)
          pos: 1.0 # position state
          vel: 100.0 # velocity state
          acc: 100.0 # acceleration state
  
        corrections: [
          "pos_aloam",
          "vel_hw_api"
        ]
  
        pos_aloam:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.01 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "nav_msgs/Odometry"
            topic: "slam/odom" # without uav namespace
            limit: 
              delay: 2.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 1.0 # [s] larger time step between messages will flag correction as unhealthy
  
          processors: [] # types of processors attached to this measurement

        vel_hw_api:
          state_id: 1 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 1.0 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "geometry_msgs/Vector3Stamped"
            topic: "hw_api/velocity" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

          median_filter:
            buffer_size: 20 # the number of samples from which the median is calculated
            max_diff: 2.0 # [m] reject measurement if difference from median is over this value

      # namespace of the heading estimator
      hdg_aloam: 

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

        position_innovation_limit: 1.0 # [m] innovation limit that will trigger switch to other estimator

        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: true
          buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)

        process_noise: # process noise covariance (Q)
          pos: 0.1 # position state
          vel: 0.1 # velocity state

        corrections: [
          "hdg_aloam"
        ]

        hdg_aloam:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.0001 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "nav_msgs/Odometry"
            topic: "slam/odom" # without uav namespace
            limit: 
              delay: 2.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 1.0 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

      # namespace of the lateral estimator
      lat_aloam: 

        hdg_source_topic: "aloam/hdg_aloam/output" # [mrs_uav_state_estimation/EstimatorOutput]

        innovation:
          limit: 1.0 # [m] innovation limit that will trigger action
          action: "switch" # {"eland", "switch", "mitigate"}

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: true
          buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)

        process_noise: # process noise covariance (Q)
          pos: 1.0 # position state
          vel: 10.0 # velocity state
          acc: 0.1 # acceleration state

        corrections: [
          "pos_aloam",
        ]

        pos_aloam:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.01 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "nav_msgs/Odometry"
            topic: "slam/odom" # without uav namespace
            limit: 
              delay: 2.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 1.0 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

  constraint_manager:

    estimator_types: [
      "aloam"
    ]

    constraints: [
      "slow",
      "medium",
      "fast",
    ]

    # list of allowed gains per odometry mode
    allowed_constraints:
      aloam: ["slow", "medium", "fast"]

    # those gains will be used automatically when a localization mode switches
    # and the current gains are not in the allowed list (next paragraphs)
    default_constraints:
      aloam: "slow"

  gain_manager:

    estimator_types: [
      "aloam"
    ]

    gains: [
      "supersoft",
    ]

    # list of allowed gains per odometry mode
    allowed_gains:
      aloam: ["supersoft"]

    # those gains will be used automatically when a localization mode switches
    # and the current gains are not in the allowed list (next paragraphs)
    default_gains:
      aloam: "supersoft"

  transform_manager:

    aloam:
      odom_topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
      tf_from_attitude: # used for transforming velocities before full transform is available
        enabled: true
        attitude_topic: "attitude" # name of the attitude topic(expects geometry_msgs/QuaternionStamped topic type)
      namespace: "estimation_manager/aloam" # the namespace of the topic (usually the node that publishes the topic)
      utm_based: false # if true, will publish tf to utm_origin
      inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
      republish_in_frames: [] # the odometry message will be transformed and republished in the specified frames

    mapping_origin_tf:
      enabled: true
      debug_prints: false
      lateral_topic: "slam/odom" # name of the topic used for x, y components of the tf (expects nav_msgs/Odometry topic type)
      altitude_topic: "slam/odom" # name of the topic  used for z components of the tf (expects nav_msgs/Odometry topic type)
      orientation_topic: "hw_api/orientation" # name of the topic  used for orientation components of the tf (expects geometry_msgs/Quaternion topic type)
      inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
      custom_frame_id:
        enabled: true
        frame_id: "mapping_origin"
