# for point cloud raycasting
sensor_params:

  3d_lidar:

    n_sensors: 1

    sensor_0:

      max_range: 20.0 # [m] max range of points to be included as occupied, free space is updated up to min(max_range, free_ray_distance)
      free_ray_distance: 15.0 # [m] max distance for free space raycasting

      # fallback values used for free space raycasting for missing data, uses pointcloud dimensions from the incoming message by default
      vertical_fov_angle: deg(90.0)
      vertical_rays: 128
      horizontal_rays: 128

      # what to do when data in the organized pointcloud is missing (is nan)
      unknown_rays:
        update_free_space: true # update free space when data at the specific point is missing?
        clear_occupied: false # clear occupied voxels using unknown rays? BEWARE, setting this to true is very DANGEROUS
        free_ray_distance_unknown: 10.0 # [m] ray length for raycasting

  depth_camera:

    n_sensors: 0

    sensor_0:

      max_range: 9.0 # [m] max range of points to be included as occupied, free space is updated up to min(max_range, free_ray_distance)
      free_ray_distance: 8.0 # [m] max distance for free space raycasting

      # fallback values used for free space raycasting for missing data, uses pointcloud dimensions and camera_info by default
      horizontal_fov_angle: deg(70.0)
      vertical_fov_angle: deg(35.0)
      horizontal_rays: 80
      vertical_rays: 45

      # what to do when data in the organized pointcloud is missing (is nan)
      unknown_rays:
        update_free_space: true # update free space when data at the specific point is missing?
        clear_occupied: false # clear occupied voxels using unknown rays? BEWARE, setting this to true is very DANGEROUS
        free_ray_distance_unknown: 5.0 # [m] ray length for raycasting

    sensor_1:

      max_range: 9.0 # [m] max range of points to be included as occupied, free space is updated up to min(max_range, free_ray_distance)
      free_ray_distance: 8.0 # [m] max distance for free space raycasting

      # fallback values used for free space raycasting for missing data, uses pointcloud dimensions and camera_info by default
      horizontal_fov_angle: deg(70.0)
      vertical_fov_angle: deg(35.0)
      horizontal_rays: 80
      vertical_rays: 45

      # what to do when data in the organized pointcloud is missing (is nan)
      unknown_rays:
        update_free_space: true # update free space when data at the specific point is missing?
        clear_occupied: false # clear occupied voxels using unknown rays? BEWARE, setting this to true is very DANGEROUS
        free_ray_distance_unknown: 5.0 # [m] ray length for raycasting
