mrs_uav_managers:

  world_origin:

    units: LATLON  # {"UTM, "LATLON"}

    origin_x: 51.853104
    origin_y: 11.397592

  safety_area_manager:

    safety_area:

      enabled: true

      horizontal:

        # the frame of reference in which the points are expressed
        frame_name: latlon_origin

        # polygon
        #
        # x, y [m] for any frame_name except latlon_origin
        # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
        points:
          - 51.8540669
          - 11.3991481
          - 51.8527306
          - 11.3995728
          - 51.8522689
          - 11.3958042
          - 51.8534400
          - 11.3954344
      vertical:

        # the frame of reference in which the max&min z is expressed
        frame_name: world_origin

        max_z: 20.0
        min_z: 1.0
