# DERIVED FROM HERE: https://earth.google.com/earth/d/1YJkZ7HL-lqSol7liQmmqarN-W4iJOjFu?usp=drive_link

mrs_uav_managers:
  world_origin:
    units: "LATLON" # {"UTM, "LATLON"}

    # rough center of the property
    origin_x: 50.184038 
    origin_y: 14.165278

  safety_area_manager:
    safety_area:

      enabled: true

      horizontal:

        # the frame of reference in which the points are expressed
        frame_name: "latlon_origin"

        # polygon
        #
        # x, y [m] for any frame_name except latlon_origin
        # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
        points: [
          50.184138, 14.165078, # NW
          50.183289, 14.164234, # SW
          50.183342, 14.164582, # SE
          50.184226, 14.165390, # NE
        ]

      vertical:
        # the frame of reference in which the max&min z is expressed
        frame_name: "world_origin"
        max_z: 35.0
        min_z: 1.0

