mrs_uav_managers:

  world_origin:

    units: LATLON  # {"UTM, "LATLON"}

    origin_x: 51.85476
    origin_y: 11.40975

  safety_area_manager:

    safety_area:

      enabled: true

      horizontal:

        # the frame of reference in which the points are expressed
        frame_name: latlon_origin

        # polygon
        #
        # x, y [m] for any frame_name except latlon_origin
        # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
        points:
          - 51.85539
          - 11.41218
          - 51.85363
          - 11.41280
          - 51.85288
          - 11.40744
          - 51.85465
          - 11.40689
      vertical:

        # the frame of reference in which the max&min z is expressed
        frame_name: world_origin

        max_z: 50.0
        min_z: 1.0
