world_origin:

  units: "LATLON"  # {"UTM, "LATLON"}

  origin_x: 51.85832
  origin_y: 11.43540

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "latlon_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      51.85917, 11.43943,
      51.85746, 11.44004,
      51.85660, 11.43360,
      51.85828, 11.43324,
    ]
  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 50.0
    min_z: 1.0
