image_width: 1600
image_height: 1200
camera_name: basler_right
camera_matrix:
  rows: 3
  cols: 3
  data: [1009.7342 ,    0.     ,  775.15777,
            0.     , 1009.67366,  587.0584 ,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.344882, 0.092028, 0.000438, -0.000527, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [725.36542,   0.     , 754.79342,   0.     ,
           0.     , 862.71991, 582.72619,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
