image_width: 1600
image_height: 1200
camera_name: basler_left
camera_matrix:
  rows: 3
  cols: 3
  data: [1025.5597 ,    0.     ,  777.1532 ,
            0.     , 1025.85919,  570.09498,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.351583, 0.093924, 0.001915, -0.001895, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [734.89355,   0.     , 749.08408,   0.     ,
           0.     , 877.49127, 561.97741,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
