name: ci_ssh_test

on:
  push:
    branches: [ ros2 ]
    paths: [ 'ssh/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Check for unencrypted ssh keys
        run: ./.ci/pre-commit
